### ISSUE TITLE
Variables named "comment" mess with syntax highlighting. 

### ISSUE THREAD

**Issue by mrmarufpro** [Shopify/liquid-tm-grammar#13]
![image](https://user-images.githubusercontent.com/39343312/203348795-6bc57fde-955b-455a-b659-7f76d39732ee.png)

I'm having trouble with liquid content highlighting like the picture. The code in the image is running fine with the theme,  but it feels like editing plain text with notepad. 

**Note:**  This problem is not appearing for other files.

I'm assuming the  `comment` and `comment.create_at` at line number 9 are causing the problem.

**Comment by charlespwd** [comment]
Hmm this seems caused by another extension you are using. The Shopify Liquid VS Code extension seems to be working fine (you should notice that liquid files have the shopify logo instead of the water droplet):

![image](https://user-images.githubusercontent.com/4990691/203363075-46d6f848-dedb-435d-afee-202897fe0971.png)
